export const YUNZAI_MANIFEST = Object.freeze({
  id: "xinghan-gacha-plugin",
  name: "米游社三游戏抽卡记录",
  platforms: Object.freeze(["Yunzai-Bot v3", "Miao-Yunzai", "TRSS-Yunzai"]),
  milestone: 6,
  commands: Object.freeze([
    "#星瀚抽卡帮助",
    "#星瀚抽卡更新",
    "#星瀚抽卡更新日志",
    "#抽卡插件状态",
    "#扫码登录",
    "#取消扫码登录",
    "#我的游戏角色",
    "#选择原神 <UID>",
    "#选择星铁 <UID>",
    "#选择绝区零 <UID>",
    "#删除米游社授权",
    "#更新原神抽卡记录",
    "#更新星铁抽卡记录",
    "#更新绝区零抽卡记录",
    "#更新全部抽卡记录",
    "#抽卡记录-查看原神抽卡记录",
    "*抽卡记录-查看HSR的",
    "%抽卡记录-查看ZZZ的",
    "#导入原神抽卡URL [UID] <URL>",
    "#导入星铁抽卡URL [UID] <URL>",
    "#导入绝区零抽卡URL [UID] <URL>",
    "#导出抽卡记录",
    "#导入抽卡记录 <UIGF JSON>",
  ]),
})
